name: Actions Workflow
on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AGENT_LABELS: test


jobs:
  run-github-actions:
    runs-on: self-hosted
    steps:
      - name: Checkout 
        uses: actions/checkout@v1
      - name: List of files
        run: |
         echo ${{ env.AGENT_LABELS }}
  
