name: Actions Workflow
on:
  push:
    branches:
      - master
  workflow_dispatch:


jobs:
  run-github-actions:
    runs-on: self-hosted
    steps:
      - name: Checkout 
        uses: actions/checkout@v1
      - name: List of files
        run: |
         echo "Sasha"
  
