name: Actions Workflow

on: [push, workflow_dispatch]


jobs:
  run-github-actions:
    runs-on: self-hosted
    steps:
      - name: Simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Sasha
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
  
