name: Actions Workflow

on: [workflow_dispatch, push]


jobs:
  run-github-actions:
    runs-on: self-hosted
    steps:
      - name: Checkout 
        uses: actions/checkout@v1
      - name: List of files
        run: |
         pwd
         ls
      - name: Simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: Sasha
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
  
