name: Actions Workflow
on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AGENT_LABELS: test


jobs:
  run-github-actions:
    runs-on: self-hosted
    steps:
      - name: Checkout 
        uses: actions/checkout@v1
      - name: List of files
        if: env.AGENT_LABELS == 'fale'
        run: |
          echo "sasha"
#      - run: |  # Test tags can be defined in inputs or in workflow env variables
#          if [ "${{ env.AGENT_LABELS }}" ]
#          then
#            echo fine
#          else
#            echo bad
#          fi
#        shell: bash


