
name: View artifact
on: [workflow_dispatch]

jobs:
  run-github-actions:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - run: mkdir -p path/to/artifact

    - run: echo hello > path/to/artifact/sasha.text

    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: path/to/artifact/sasha.text
