name: Docker-image

on: push 

jobs: 
  container-job:
    runs-on: self-hosted
    steps:
      - name: Get current directory path
        run: |
          pwd
          ls
    container:
      image: golang:1.13-alpine
    env:
      SAA: Done it
      - name: print Env value
        run: |
          echo $SAA
          pwd

    
  
