name: Docker-image

on: push 

jobs: 
  container-job:
    runs-on: self-hosted
    steps:
      - name: Checkout last git changes
        uses: actions/checkout@v1
      - name:
        uses: ./.github/actions/build_code

    
  
