name: container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.10
    steps:
      - name: View current directory
        run: |
          pwd
          ls
      - name: Checkout Project
        uses: actions/checkout@v1
      - name: View current directory
        run: |
          pwd
          ls
      - name: Install docker inside pipeline
        run: |
          apk add --update docker openrc
          rc-update add docker boot
      - name: Pull golang:1.13-alpine docker image
        run: sudo docker pull golang:1.13-alpine
      - name: Compile the code into an executable
        run: docker run --rm --privileged -e "CGO_ENABLED=0" -e "GOFLAGS=-mod=vendor -ldflags=-s -trimpath"  --net=host golang:1.13-alpine sh -c "pwd"