name: container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.10
    steps:
      - name: View current directory
        run: |
          pwd
          ls
#      - name: Checkout Project
#        uses: actions/checkout@v1
#      - name: View current directory
#      - run: |
#          pwd
#          ls