name: Docker-image

on: push 

jobs: 
  container-job:
    runs-on: self-hosted
    container:
      image: golang:1.13-alpine
    env:
      SAA: Done it
    steps:
      - name: print Env value
        run: |
          echo $SAA  
    
  
