name: container
on: push

jobs:
  node-docker:
    runs-on: self-hosted
    container:
      image: golang:1.13-alpine
      env:
        TUT: 2
        VUV: 3
    steps:
      - name: Remove all files from workspace
        run: |
          shopt -s dotglob
          rm -rf *
      - name: View current directory
        run: |
          cat /etc/os-release
          echo $TUT
          echo {$VUV}
          echo $TUT_$VUV
          echo $TUT\_$VUV
          echo $TUT/_$VUV

#      - name: Install docker inside pipeline
#        run: |
#          apk add --update docker openrc
#          rc-update add docker boot
#      - name: Pull golang:1.13-alpine docker image
#        run: docker pull golang:1.13-alpine
#      - name: Checkout Project
#        uses: actions/checkout@v1
#      - name: view conteng
#        run: |
#          pwd
#          ls $GITHUB_WORKSPACE
#          echo $GITHUB_WORKSPACE
#      - name: Compile the code into an executable
#        run: docker run --rm --privileged -e "CGO_ENABLED=0" -e "GOFLAGS=-mod=vendor -ldflags=-s -trimpath"  --net=host -v $GITHUB_WORKSPACE:/root/work -w /root/work golang:1.13-alpine sh -c "ls && pwd"