name: Manual Inputs
on: 
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        default: v1.0.0
        required: true
      file:
        description: File version
        default: Real
        required: true
      dream:
        description: Email field
        default: email
        required: true
env:
  WF_ENV: ${{ github.event.inputs.dream }}
  
jobs:
  bump-version:
    name: Bump Package Version
    runs-on: self-hosted
    steps:
      - name: Example variable usage
        run: |
          echo ${{ github.event.inputs.version }}
          echo ${{ github.event.inputs.file }}
          env
